Enable the user to support hold foreign units.
codazen/webDiplomacy pull request #105
Opened 2022-05-03 00:29 UTC by bryancodazen

### Summary
This PR enables users to support hold a foreign unit. 

To support hold a foreign unit the user must do the following:
1. double click the supporting unit
2. single click the foreign unit being supported
3. single click the territory the foreign unit is on

### Video
https://drive.google.com/file/d/1XUCNQGrxfFf5KfprwJaGfSVu6Pa4EJ5V/view?usp=sharing

2022-05-03 20:49 UTC, mariomelchor requested changes

2022-05-03 20:49 UTC, mariomelchor commented on beta-src/src/components/ui/WDUnitController.tsx
>    const clickAction = (e) => {
both clickAction and doubleClickAction are nearly identical now only thing that change is the method. Can we consolidate and pass another parameter to this method.

2022-05-03 20:49 UTC, mariomelchor commented on beta-src/src/state/game/game-api-slice.ts
>          } else if (
This else if statement is doing the same thing for both checks. Can we do an `||` statement in the first check to include `type === "move" && toTerritory !== null`

2022-05-04 00:32 UTC, mariomelchor approved these changes
LGTM

2022-05-04 00:37 UTC, sariacodazen approved these changes
LGTM

2022-05-04 02:09 UTC, merged