Hotfix/webdip rr bugs
codazen/webDiplomacy pull request #133
Opened 2022-05-17 00:01 UTC by sariacodazen

This PR address forced retreat, units being placed in proper territories during retreats phase, and saving orders during forced disband

Test Plan: 
Pull code
Put game in retreats phase with only one option (game should force draw a retreat arrow to that territory)
Put a unit in a position with nowhere to retreat (unit should show disbanded icon and order state in context should show Saved,Completed" and Save button should be unclickable)

2022-05-17 19:57 UTC, bryancodazen requested changes

2022-05-17 19:57 UTC, bryancodazen commented on beta-src/src/utils/map/getUnits.ts
>        contextVars?.context.phase === "Retreats"
Don't use contextVars for phase data, use the phase in game overview instead.

2022-05-17 19:57 UTC, bryancodazen commented on beta-src/src/utils/map/updateUnitsRetreat.ts
> +
Don't use orderStates, use gameOverview -> user -> member -> orderStatus

2022-05-17 19:57 UTC, bryancodazen commented on beta-src/src/components/ui/WDMoveControls.tsx
> +  };
I think you need to delete the command after it is processed. Look at the command actions in WDTerritory, WDMapController, or WDUnitController as examples.

2022-05-17 21:26 UTC, mariomelchor requested changes

2022-05-17 21:26 UTC, mariomelchor commented on beta-src/src/utils/map/updateUnitsRetreat.ts
> +      !orderStates?.Completed
If you get this from state orderStates wouldn't be null.

2022-05-18 00:27 UTC, bryancodazen requested changes
We should not be able to select other units (that don't have retreat orders) during the retreats phase. 

https://user-images.githubusercontent.com/93741108/168933187-3ab98ef0-c2f0-47a1-8465-e1697911317d.mov

2022-05-18 00:57 UTC, bryancodazen requested changes
Ran into another issue as well where the unit only has one place to retreat to (Picardy), yet the arrow is not getting drawn (the order is not being set in ordersMeta either).


https://user-images.githubusercontent.com/93741108/168935583-41258669-a920-46ba-bdd5-90e139a958b3.mov

2022-05-18 23:29 UTC, bryancodazen approved these changes
lgtm

2022-05-18 23:30 UTC, justinyoocodazen approved these changes

2022-05-18 23:44 UTC, merged