Feature/fbfw 143 transition to next phase
codazen/webDiplomacy pull request #151
Opened 2022-05-23 19:05 UTC by justinyoocodazen

To test:

Upon refreshing or page load, loading screen should render. Likewise, when everyone is ready, run gamemaster and the react app should transition to the next phase while displaying the loading screen.

Due to time constraints, fake loading times was not implemented. WDUI is also not rendered during transitions to prevent actions being taken.

2022-05-23 22:01 UTC, mariomelchor requested changes

2022-05-23 22:01 UTC, mariomelchor commented on beta-src/src/state/game/game-api-slice.ts
> +        state.transition = true;
if we add it it to this case `fetchGameData.rejected` wouldn't this cause the loading screen to always stay on.

2022-05-23 22:01 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
everything is fixed in here. Can we have a fixed wrapper and then position elements based of the fixed wrapper via flex?

2022-05-23 22:01 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
everything is fixed in here. Can we have a fixed wrapper and then position elements based of the fixed wrapper via flex?

2022-05-23 22:01 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
Can this be position abolute?

2022-05-23 22:01 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
Can this be position abolute?

2022-05-23 22:49 UTC, justinyoocodazen commented on beta-src/src/state/game/game-api-slice.ts
> +        state.transition = true;
I was thinking if the gamefetchdata failed than the loading screen should stay on

2022-05-23 22:58 UTC, justinyoocodazen commented on beta-src/src/state/game/game-api-slice.ts
> +        state.transition = true;
probably make them refresh

2022-05-24 19:04 UTC, mariomelchor requested changes
Logic looks good just some layout changes. Were you able to investigate more on the 3s delay?

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/state/game/game-api-slice.ts
> +        state.transition = true;
if we add it it to this case `fetchGameData.rejected` wouldn't this cause the loading screen to always stay on.

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          alignItems: "center",
Don't think we need flex here since its just the image and loading animation is just stacked.

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          alignItems: "center",
Don't think we need flex here since its just the image and loading animation is just stacked.

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
this can just be absolute position

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          position: "fixed",
this can just be absolute position

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          height: 60,
let the content dictate the height. We can control the height with padding on the inner container

2022-05-24 19:04 UTC, mariomelchor commented on beta-src/src/components/ui/WDTransition.tsx
> +          height: 60,
let the content dictate the height. We can control the height with padding on the inner container

2022-05-24 20:30 UTC, justinyoocodazen commented on beta-src/src/components/ui/WDTransition.tsx
> +          alignItems: "center",
This lines it up with the image, at first I tried making 'loading' and the progress bar children of the image to make less css necessary but I got an error saying that you can't make other boxes children of images.

2022-05-24 20:42 UTC, justinyoocodazen commented
@mariomelchor I think faking loading times is pretty against react's whole based on state thing so everything I found wasn't useful. It still does show for a decent enough time so I think it's fine without any extra time

2022-05-24 22:13 UTC, mariomelchor approved these changes
LGTM

2022-05-25 01:27 UTC, sariacodazen approved these changes
LGTM

2022-05-25 16:23 UTC, merged