feature/fbfw-69/game-phase-icon
codazen/webDiplomacy pull request #28
Opened 2022-03-01 18:09 UTC by jchoi166

Demo link: 
https://happy-lumiere-e2eab6.netlify.app/

2022-03-01 18:49 UTC, hyukcodazen approved these changes
LGTM!
Maybe we can think about "enabled" prop to be handled within component as a state.

2022-03-02 18:02 UTC, nebevets requested changes
just a few nits to clean up

2022-03-02 20:08 UTC, jchoi166 commented
@bryancodazen LOL I though it was weird that Hyuk reviewed my PR instead of you. I guess I mis-clicked on the name. 

Everything has been updated with the requested changes. There are a lot of commits on this PR because I initially requested to merge this branch into FBFW-60 like a dum dum for some reason. I changed it so that its merging back into staging, but I had to clean up the code a bit so that it wouldn't have any merge conflicts.

2022-03-02 21:29 UTC, bryancodazen requested changes

2022-03-02 21:29 UTC, bryancodazen commented on beta-src/src/enums/Season.ts
> +  ENABLED = "Enabled",
This doesn't belong here.

2022-03-02 21:29 UTC, bryancodazen commented on beta-src/src/components/svgr-components/WDGamePhaseIcon.tsx
> +  iconState: Season;
I don't know that I understand the relationship between iconState and seasons. Naming seems off here.

2022-03-03 19:33 UTC, bryancodazen commented
> @bryancodazen LOL I though it was weird that Hyuk reviewed my PR instead of you. I guess I mis-clicked on the name.
> 
> Everything has been updated with the requested changes. There are a lot of commits on this PR because I initially requested to merge this branch into FBFW-60 like a dum dum for some reason. I changed it so that its merging back into staging, but I had to clean up the code a bit so that it wouldn't have any merge conflicts.

It's great that others review the PRs, when creating a PR you want to add everyone working on web dip as reviewers.

2022-03-03 20:12 UTC, jchoi166 commented
@nebevets Github isn't letting me re-request a review from you, so pinging you here!

2022-03-04 19:41 UTC, bryancodazen approved these changes

2022-03-07 18:42 UTC, nebevets approved these changes
LGTM

2022-03-08 18:35 UTC, merged